const FACTS: Record<string, string> = {
  TIGER: 'Tigers can sprint up to 40 mph — but only for short bursts.',
  EAGLE: 'Eagles can see prey from two miles away.',
  WHALE: 'Blue whales are the largest animals ever known to have lived.',
  DOLPHIN: 'Dolphins sleep with one eye open — half their brain stays awake.',
  PENGUIN: 'Emperor penguins can dive over 500 meters deep.',
  PANDA: 'Giant pandas spend up to 14 hours a day eating bamboo.',
  SHARK: 'Sharks have existed for more than 400 million years.',
  OCTOPUS: 'Octopuses have three hearts and blue blood.',
  GIRAFFE: 'A giraffe’s tongue can be up to 50 cm long.',
  KOALA: 'Koalas sleep up to 20 hours a day.',
  ZEBRA: 'Every zebra’s stripe pattern is unique, like a fingerprint.',
  RABBIT: 'A rabbit’s teeth never stop growing.',
  HORSE: 'Horses can sleep both standing up and lying down.',
  PIZZA: 'The first pizza delivery is believed to date back to 1889 in Naples.',
  SUSHI: 'Sushi originally began as a method of preserving fish in fermented rice.',
  BANANA: 'Bananas are berries; strawberries are not.',
  HONEY: 'Honey never spoils — edible honey was found in ancient Egyptian tombs.',
  CHEESE: 'There are over 1,800 different types of cheese worldwide.',
  CHOCOLATE: 'Cacao beans were once used as currency by the Maya.',
  COFFEE: 'Coffee is the second most traded commodity after oil.',
  PASTA: 'There are more than 300 shapes of pasta.',
  APPLE: 'Apples float because they are 25% air.',
  LEMON: 'Lemon trees can produce fruit year-round in warm climates.',
  SOCCER: 'Soccer is played by over 250 million people in more than 200 countries.',
  TENNIS: 'A tennis match can last over 11 hours — the longest on record.',
  MARATHON: 'The marathon distance was standardized at 26.2 miles for the 1908 Olympics.',
  HOCKEY: 'Ice hockey pucks are frozen before games to reduce bouncing.',
  GOLF: 'Golf is one of the few sports that can be played into old age.',
  SWIMMING: 'Swimming works nearly every muscle group at once.',
  OSCAR: 'The Oscar statuette weighs 8.5 pounds and is gold-plated bronze.',
  COMEDY: 'The first known comedy film dates to 1895.',
  CAMERA: 'The word camera comes from Latin “camera obscura” — dark chamber.',
  CINEMA: 'The first public cinema screening was in Paris in 1895.',
  PARIS: 'Paris has been the capital of France for over 1,000 years.',
  TOKYO: 'Tokyo is the most populous metropolitan area in the world.',
  DESERT: 'Antarctica is technically the world’s largest desert.',
  VOLCANO: 'There are more than 1,500 potentially active volcanoes worldwide.',
  OCEAN: 'Over 80% of the ocean remains unexplored.',
  RIVER: 'The Nile and Amazon compete for title of longest river.',
  MOUNTAIN: 'Mount Everest grows a few millimeters each year.',
  CHRISTMAS: 'Christmas trees became popular in the 16th century in Germany.',
  HALLOWEEN: 'Halloween traces roots to the Celtic festival of Samhain.',
  RAINBOW: 'A double rainbow reverses the color order in the outer arc.',
  DRAGON: 'Dragon myths appear independently in cultures across every continent.',
  CASTLE: 'Some castles took decades — or centuries — to complete.',
  MAGIC: 'Stage magic relies more on psychology than on secret devices.',
  ATOM: 'Atoms are mostly empty space.',
  DNA: 'If uncoiled, DNA from one cell would stretch about two meters.',
  GENE: 'Humans share about 60% of their genes with bananas.',
  LASER: 'LASER stands for Light Amplification by Stimulated Emission of Radiation.',
  GRAVITY: 'Gravity is the weakest of the four fundamental forces — but shapes the cosmos.',
  PLANET: 'A planet must clear its orbital neighborhood of other debris.',
  GALAXY: 'The Milky Way contains roughly 100–400 billion stars.',
  COMET: 'Comet tails always point away from the sun.',
  MOON: 'The Moon is drifting away from Earth about 3.8 cm per year.',
  STAR: 'Most stars we see are larger and brighter than our Sun.',
  NEBULA: 'Nebulae are stellar nurseries where new stars form.',
  PIANO: 'A full piano has 88 keys spanning over seven octaves.',
  VIOLIN: 'A violin has four strings tuned in perfect fifths.',
  GUITAR: 'The modern guitar evolved from earlier stringed instruments in Spain.',
  SYMPHONY: 'A typical symphony has four movements.',
  MELODY: 'Melody is often what listeners remember most from a song.',
  RHYTHM: 'Rhythm is one of the few musical elements shared by every culture.',
  FOREST: 'Forests cover about 31% of the world’s land surface.',
  TREE: 'Some trees can live for thousands of years.',
  FLOWER: 'Flowers evolved to attract pollinators with color and scent.',
  STORM: 'Lightning can heat air to five times hotter than the sun’s surface.',
  BOOK: 'The oldest known printed book is the Diamond Sutra (868 CE).',
  POEM: 'Poetry predates written history — it began as oral tradition.',
  NOVEL: 'The modern novel form took shape in the 17th–18th centuries.',
  STORY: 'Storytelling is found in every known human culture.',
  AUTHOR: 'Many classic authors published under pen names.',
  LIBRARY: 'The Library of Alexandria was among the ancient world’s greatest.',
  CHAPTER: 'Chapter breaks help readers rest and writers structure plot.',
  HERO: 'The hero’s journey is a story pattern found worldwide.',
  CORAL: 'Coral reefs support about 25% of marine species.',
  REEF: 'The Great Barrier Reef is visible from space.',
  SPACE: 'Sound cannot travel through the vacuum of space.',
  EARTH: 'Earth is the only known planet with liquid water on its surface.',
  MARS: 'A day on Mars is about 40 minutes longer than on Earth.',
  JUPITER: 'Jupiter has at least 90 known moons.',
  SATURN: 'Saturn’s rings are mostly ice particles.',
  SUN: 'Light from the Sun takes about 8 minutes to reach Earth.',
  NEST: 'Bald eagles build nests that can weigh over a ton.',
};

export function getWordFact(word: string): string | null {
  return FACTS[word.toUpperCase()] ?? null;
}

export function getGenericFact(category: string): string {
  const generics: Record<string, string> = {
    animals: 'Scientists discover thousands of new species every year.',
    food: 'The average person makes over 200 food-related decisions daily.',
    sports: 'The Olympic Games have been held every four years since 1896.',
    movies: 'The first movie with synchronized sound was The Jazz Singer in 1927.',
    geography: 'There are 195 countries recognized by the United Nations.',
    kids: 'Children ask an average of 300 questions per day.',
    holiday: 'Over 2 billion people celebrate Christmas worldwide.',
    science: 'Your body has around 37 trillion cells working in concert.',
    music: 'The oldest known musical instrument is over 40,000 years old.',
    nature: 'A single mature oak tree can support hundreds of species.',
    space: 'There are more stars in the universe than grains of sand on Earth.',
    books: 'The longest novel ever published has over 9 million words.',
    mythology: 'Greek mythology alone has hundreds of named gods and heroes.',
    history: 'The Rosetta Stone unlocked the reading of Egyptian hieroglyphs.',
    travel: 'The first commercial jet airliner flew in 1952.',
    technology: 'The first website went live in 1991 at CERN.',
  };
  return generics[category] ?? 'Every word has a story waiting to be discovered.';
}
