/**
 * Expand thin category banks + pack pools, dedupe, rewrite sources.
 * Run: node scripts/expand-content.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const EXTRA = {
  mythology: `
ATLAS GAEA CRONUS RHEA PROMETHEUS EPIMETHEUS PANDORA ECHO NARCISSUS
ICARUS DAEDALUS THESEUS ARIADNE JUNO JUNIPER VESTA CERES BACCHUS VULCAN
NEPTUNE PLUTO MERCURY VENUS MARS MINERVA CUPID PSYCHE ADONIS ENDYMION
HELIOS SELENE EOS IRIS NIKE TYCHE HECATE NEMESIS HYPNOS THANATOS MORPHEUS
AETHER CHAOS GAIA URANUS PONTUS TARTARUS STYX LETHE ACHERON EREBUS
NYX HEMERA CHIRON CHARON SCYLLA CHARYBDIS ARGUS HYDRA LADON PYTHON
NEMEAN CERBERUS GORGON HARPY FURY SIREN MERMAID DRYAD OREAD NAIAD
OCEANID TITANESS AMAZON WARRIOR DEMIGOD DEMIGODDESS ORACLE SEER
PRIESTESS TEMPLE ALTAR SACRIFICE OFFERING LIBATION HYMN CHANT RITUAL
PROPHECY FATE DESTINY DOOM HEROISM VALOR GLORY HONOR OATH PLEDGE
QUEST VOYAGE ODYSSEY EXILE BANISHMENT UNDERWORLD AFTERLIFE ELYSIUM
VALHALLA BIFROST MIDGARD JOTUNHEIM NIFLHEIM MUSPELHEIM YGGDRASIL
FENRIR JORMUNGANDR SLEIPNIR MJOLNIR GUNGNIR HUGINN MUNINN BALDR
TYR HEIMDALL FRIGG FREYR NJORD HEL SURT FAFNIR SIEGFRIED BEOWULF
GRYPHON DRAGON WYVERN KRAKEN LEVIATHAN BEHEMOTH CHIMERA MANTICORE
UNICORN BASILISK COCKATRICE GOLEM DJINN IFRIT PHOENIX REBIRTH ASCENSION
IMMORTALITY MORTALITY DIVINE SACRED HOLY BLESSED CURSED ENCHANTMENT
SPELL CHARM AMULET TALISMAN RELIC ARTIFACT LEGEND MYTHOS EPIC
BALLAD SAGA CHRONICLE SCROLL TABLET RUNESTONE CUNEIFORM HIEROGLYPH
`,
  history: `
PHARAOH CLEOPATRA RAMSES TUTANKHAMUN NEFERTITI MESOPOTAMIA BABYLON
ASSYRIA PERSIA GREECE ROME CARTHAGE SPARTA ATHENS ALEXANDER CAESAR
AUGUSTUS CONSTANTINE CHARLEMAGNE NAPOLEON WASHINGTON LINCOLN CHURCHILL
GHANDI MANDELA CLEOPATRA CLEOPATRA REVOLUTION REBELLION UPRISING COUP
MONARCHY OLIGARCHY THEOCRACY REPUBLIC COMMONWEALTH FEDERATION UNION
CONFEDERACY PROVINCE COLONY TERRITORY FRONTIER PIONEER SETTLER HOMESTEAD
WAGON RAILROAD TELEGRAPH INDUSTRY FACTORY STEAM ENGINE LOCOMOTIVE
PRINTING PRESS GUTENBERG RENAISSANCE ENLIGHTENMENT REFORMATION BAROQUE
VICTORIAN EDWARDIAN GEORGIAN TUDOR STUART HANOVER PLANTAGENET NORMAN
SAXON VIKING RAIDER LONGSHIP FJORD NORDIC CELTIC PICTISH GAUL
FRANKISH VISIGOTH OSTROGOTH HUN MONGOL HORDE KHAN SILK ROAD SPICE
TRADE MERCHANT GUILD CRAFTSMAN ARTISAN BLACKSMITH MASON SCRIBE MONK
ABBEY CATHEDRAL MOSQUE SYNAGOGUE PAGODA SHRINE TOMB MAUSOLEUM CRYPT
BATTLEFIELD TRENCH FORTRESS CITADEL BASTION RAMPART DRAWBRIDGE MOAT
CATAPULT TREBUCHET BALLISTA CROSSBOW LONGBOW MUSKET RIFLE CANNONADE
ARMADA FLEET GALLEON FRIGATE BATTLESHIP DESTROYER SUBMARINE CARRIER
INFANTRY CAVALRY ARTILLERY CAVALRY ARCHER SPEARMAN SWORDSMAN KNIGHT
SQUIRE PAGE CASTLE KEEP TOWER DUNGEON THRONE CROWN SCEPTER ORB
PARCHMENT QUILL INK SEAL CHARTER MAGNA CARTA BILL RIGHTS CONSTITUTION
AMENDMENT SUFFRAGE ABOLITION EMANCIPATION RECONSTRUCTION DEPRESSION
WARFARE ARMISTICE CEASEFIRE SURRENDER VICTORY DEFEAT OCCUPATION LIBERATION
DIPLOMAT TREATY ALLIANCE PACT COALITION EMBARGO SANCTION NEUTRALITY
EMPIRE COLONIALISM IMPERIALISM NATIONALISM PATRIOTISM HERITAGE LEGACY
ARCHIVE MUSEUM EXHIBIT CURATOR HISTORIAN SCHOLAR CHRONICLE ANNALS
`,
  travel: `
SUITCASE CARRYON BACKPACK DUFFEL RUCKSACK TOTE HANDBAG WALLET PASSPORT
VISA STAMP CUSTOMS IMMIGRATION BORDER CHECKPOINT GATE TERMINAL CONCOURSE
RUNWAY TAXIWAY HANGAR COCKPIT AISLE SEATBELT TRAYTABLE OVERHEAD BIN
BOARDING PASS BAGGAGE CLAIM CAROUSEL TROLLEY PORTER CONCIERGE BELLHOP
RECEPTION LOBBY SUITE PENTHOUSE BUNGALOW VILLA CHALET COTTAGE CABANA
CAMPSITE TENT SLEEPINGBAG HAMMOCK RIVERBOAT CATAMARAN YACHT LINER
FERRY HYDROFOIL MONORAIL TRAM TROLLEYBUS RIDESHARE SCOOTER BICYCLE
TRAILHEAD SWITCHBACK SUMMIT RIDGELINE VALLEY CANYON GORGE RAVINE
PLATEAU MESA BUTTE GLACIER FJORDS ARCHIPELAGO ATOLL PENINSULA ISTHMUS
COASTLINE SHORELINE BOARDWALK PROMENADE ESPLANADE MARINA QUAY WHARF
BAZAAR SOUK MARKETPLACE BOUTIQUE SOUVENIR KEEPSAKE POSTCARD STAMP
ITINERARY BOOKING RESERVATION CONFIRMATION CANCELLATION DELAY LAYOVER
CONNECTION TRANSIT TRANSFER STOPOVER DAYTRIP EXCURSION TOUR OUTING
SAFARI EXPEDITION TREK HIKE CLIMB SCUBA SNORKEL KAYAK PADDLE RAFT
ZIPLINE PARASAIL HANGGLIDE BUNGEE SKYDIVE SURF SAIL WINDSURF KITE
PHOTOGRAPHY SELFIE LANDSCAPE SUNRISE SUNSET GOLDENHOUR TWILIGHT DAWN
HORIZON SKYLINE CITYSCAPE STREETSCAPE NEIGHBORHOOD DISTRICT QUARTER
DOWNTOWN UPTOWN OLDTOWN HARBOR WATERFRONT SEASIDE LAKESIDE RIVERSIDE
MOUNTAIN PASS TUNNEL BRIDGE VIADUCT AQUEDUCT LOOKOUT VIEWPOINT SCENIC
CULTURE CUISINE LANGUAGE DIALECT CUSTOM TRADITION FESTIVAL CARNIVAL
PARADE PROCESSION CEREMONY RITUAL WELCOME HOSPITALITY HOST GUEST LOCAL
GUIDEBOOK MAP COMPASS GPS NAVIGATE ORIENT EXPLORE DISCOVER WANDER
ROAM DRIFT MEANDER JOURNEY ODYSSEY ADVENTURE ESCAPADE GETAWAY RETREAT
VACATION HOLIDAY TRIP TOURISM TOURIST TRAVELER WANDERLUST NOMAD EXPAT
`,
  technology: `
PROCESSOR MICROCHIP TRANSISTOR SEMICONDUCTOR INTEGRATED CIRCUIT BOARD
MOTHERBOARD FIRMWARE BOOTLOADER KERNEL DRIVER MODULE LIBRARY FRAMEWORK
RUNTIME COMPILER INTERPRETER DEBUGGER PROFILER REPOSITORY BRANCH COMMIT
MERGE PULLREQUEST CODEBASE REFACTOR DEPLOYMENT PIPELINE CONTAINER DOCKER
KUBERNETES SERVERLESS MICROSERVICE API ENDPOINT PAYLOAD JSON XML YAML
DATABASE TABLE INDEX QUERY TRANSACTION CACHE REDIS MEMCACHED CDN EDGE
LATENCY BANDWIDTH THROUGHPUT PACKET PROTOCOL TCP UDP HTTP HTTPS SSH
TLS SSL CERTIFICATE ENCRYPTION DECRYPTION HASHING SALT TOKEN OAUTH
PASSWORD PASSPHRASE BIOMETRIC FINGERPRINT FACEID TWOFACTOR AUTH LOGIN
LOGOUT SESSION COOKIE STORAGE LOCALSTORAGE INDEXEDDB WEBASSEMBLY WASM
FRONTEND BACKEND FULLSTACK REACT VUE ANGULAR SVELTE TYPESCRIPT PYTHON
RUST GOLANG SWIFT KOTLIN JAVA RUBY PHP SCALA HASKELL ELIXIR
ALGORITHM SORT SEARCH GRAPH TREE HEAP QUEUE STACK RECURSION ITERATION
MACHINELEARNING NEURAL NETWORK TENSOR MODEL TRAINING INFERENCE DATASET
CLUSTERING CLASSIFY REGRESSION OVERFIT UNDERFIT VALIDATION ACCURACY
ROBOTICS ACTUATOR SERVO MOTOR ENCODER GYROSCOPE ACCELEROMETER LIDAR
RADAR ULTRASONIC INFRARED BLUETOOTH WIFI CELLULAR SATELLITE UPLINK
DOWNLINK MODEM ROUTER SWITCH HUB FIREWALL PROXY VPN TUNNEL MESH
SMARTPHONE TABLET LAPTOP DESKTOP WORKSTATION MAINFRAME SUPERCOMPUTER
QUANTUM QUBIT ENTANGLE SUPERPOSITION OBSERVE MEASURE SIMULATE RENDER
PIXEL VECTOR SHADER TEXTURE MESH POLYGON VERTEX FRAGMENT RAYTRACE
AUGMENTED VIRTUAL MIXED REALITY HEADSET CONTROLLER HAPTIC FEEDBACK
WEARABLE SMARTWATCH EARBUD HEADPHONE MICROPHONE WEBCAM PROJECTOR DISPLAY
MONITOR RESOLUTION REFRESH RATE ASPECT RATIO CONTRAST BRIGHTNESS HDR
PRINTER SCANNER COPIER FAX MODEM CABLE FIBER OPTIC COPPER WIRELESS
BATTERY LITHIUM CHARGE DISCHARGE VOLTAGE CURRENT WATTAGE AMPERE OHM
SENSOR ACTUATOR RELAY SWITCH BUTTON TOUCHSCREEN STYLUS TRACKPAD SCROLL
AUTOMATION SCRIPT BOT CRAWLER SPIDER SCRAPER PARSER TOKENIZER PARSER
CLOUD HYBRID MULTICLOUD ONPREM DATACENTER RACK SERVER BLADE NODE
BACKUP SNAPSHOT RESTORE FAILOVER REDUNDANCY REPLICATION MIRROR SYNC
UPDATE PATCH HOTFIX RELEASE VERSION SEMVER CHANGELOG NOTES DEPRECATE
`,
  movies: `
CINEMA THEATER SCREENPLAY SCRIPTWRITER DIRECTOR PRODUCER CINEMATOGRAPHER
EDITOR COMPOSER SOUNDTRACK SCORE DIALOGUE MONOLOGUE SOLILOQUY VOICEOVER
NARRATION SUBTITLE CAPTION DUBBING FOLEY ADR MIXING MASTERING CUT
TAKE SCENE SEQUENCE ACT INTERMISSION PREVIEW TRAILER TEASER POSTER
BILLBOARD MARQUEE TICKET USHER POPCORN SODA CANDY CONCESSION LOBBY
BLOCKBUSTER INDIE FESTIVAL OSCAR EMMY GOLDEN GLOBE BAFTA SUNDANCE
CANNES VENICE TORONTO TRIBECA PREMIERE REDCARPET PAPARAZZI FLASHBULB
CAMERA LENS BOOM MICROPHONE CRANE DOLLY STEADICAM TRIPOD REFLECTOR
LIGHTING KEYLIGHT FILL LIGHT BACKLIGHT SILHOUETTE SHADOW DEPTH FOCUS
APERTURE SHUTTER EXPOSURE FRAME RATE ASPECT RATIO WIDESCREEN IMAX
ANIMATION STOPMOTION CLAYMATION CGI PIXELART STORYBOARD ANIMATIC REEL
DOCUMENTARY BIOGRAPHY DRAMA COMEDY ROMCOM THRILLER HORROR SUSPENSE
WESTERN NOIR NEOREALISM SURREAL AVANTGARDE EXPERIMENTAL SHORTFILM
FEATURE LENGTH SERIAL ANTHOLOGY TRILOGY SAGA FRANCHISE SEQUEL PREQUEL
REMAKE REBOOT SPINOFF CROSSOVER CAMEO EXTRAS STUNT DOUBLE STANDIN
PROTAGONIST ANTAGONIST SIDEKICK MENTOR FOIL ARCHENEMY CLIFFHANGER TWIST
PLOT HOLE MACGUFFIN MONTAGE FLASHBACK FLASHFORWARD DREAM SEQUENCE
FADE DISSOLVE WIPE CUTAWAY JUMPCUT MATCHCUT CROSSCUT PARALLEL EDIT
BOXOFFICE GROSS BUDGET OPENING WEEKEND MATINEE MIDNIGHT SCREENING
CRITIC REVIEW ROTTEN TOMATOES METACRITIC RATING STAR SPOILER ALERT
`,
  holiday: `
FESTIVAL CELEBRATION GATHERING REUNION FEAST BANQUET TOAST CHEERS
GIFTBOX RIBBON BOW WRAPPER TAG CARD ENVELOPE LETTER NOTE WISH
WISHLIST STOCKING STUFFER SURPRISE PRESENT UNWRAP OPENING PARTY
CONFETTI STREAMER BALLOON BANNER BUNTING LANTERN FAIRYLIGHT STRING
CANDLELIGHT MENORAH KINARA ADVENT WREATH GARLAND MISTLETOE HOLLY
IVY PINE CONE EVERGREEN FIR SPRUCE CEDAR CYPRESS BERRY POINSETTIA
SNOWFLAKE ICICLE FROST GLITTER SPARKLE SHIMMER TWINKLE GLOW
FIREWORK SPARKLER FIRECRACKER PARADE FLOAT MARCH BAND MUSIC
CAROL HYMN CHANT ANTHEM DANCE REEL JIG WALTZ POLKA CHA
FEAST TABLE SETTING PLACEMAT NAPKIN CENTERPIECE CANDLESTICK VASE
TURKEY HAM ROAST GRAVY STUFFING CRANBERRY YAM PIE PUMPKIN
APPLECIDER EGGNOG MULLED WINE CHAMPAGNE TOAST SPARKLING CIDER
COOKIE GINGERBREAD SHORTBREAD FUDGE TRUFFLE CANDYCANE PEPPERMINT
CHOCOLATE COCOA MARSHMALLOW HOTCHOCOLATE LATTE SPICED CHAI
ORNAMENT BAUBLE TINSEL TREE TOPPER STAR ANGEL BELLS CHIME
SLEIGH BELLS REINDEER RUDOLPH SANTA CLAUS MRSCLAUS ELVES WORKSHOP
NORTHPOLE CHIMNEY HEARTH FIREPLACE MANTEL STOCKING HOOK
NEWYEAR COUNTDOWN MIDNIGHT RESOLUTION KISS TOAST SPARKLER
VALENTINE HEART CUPID ROSE CHOCOLATE BOX LOVE NOTE ROMANCE
EASTER BASKET EGG HUNT BUNNY CHICK PASTEL SPRING BLOOM
HALLOWEEN COSTUME MASK CANDY TRICK TREAT JACKOLANTERN PUMPKIN
THANKSGIVING GRATITUDE HARVEST CORNUCOPIA PILGRIM FEAST FAMILY
INDEPENDENCE FIREWORKS FLAG PATRIOT PARADE PICNIC BARBECUE
HANUKKAH DREIDEL LATKE MENORAH MIRACLE OIL LIGHTS BLESSING
KWANZAA UMOJA KUJICHAGULIA UJIMA UJAMAA NIA KUUMBA IMANI
DIWALI DIYA RANGOLI SWEETS LANTERN LIGHT FESTIVAL JOY
`,
  movies_more: `
CINEPHILE FILMMAKER AUTEUR NOIR MELODRAMA FARCE SATIRE PARODY
HOMAGE TRIBUTE SPOOF MOCKUMENTARY DOCUDRAMA BIOPIC WARFILM
MUSICAL OPERETTA BALLET CONCERT FILM EXPERIMENTAL ABSTRACT
PROJECTION REELTOREEL CELLULOID NITRATE DIGITAL 4K 8K HDR
DOLBY SURROUND STEREO MONO THX IMAX DOME PLANETARIUM SCREEN
`,
  kids: `
PLAYGROUND SWINGSET SLIDE SEESAW SANDBOX MONKEYBARS TRAMPOLINE
BUBBLE CHALK CRAYON MARKER GLITTER STICKER STAMP STAMP PAD
PUZZLE BLOCKS LEGO TRAINSET DOLLHOUSE ACTIONFIGURE PLUSHIE TEDDY
STORYTIME BEDTIME LULLABY NIGHTLIGHT STUFFED ANIMAL BLANKET FORT
SCOOTER SKATE TRICYCLE BICYCLE HELMET KNEEPADS ELBOWPADS GLOVES
JUNGLEGYM CLIMB CRAWL JUMP SKIP HOP GALLOP RACE TAG FREEZE
HIDESEEK HOPSCOTCH JUMPROPE MARBLES YOYO FRISBEE KITE BOOMERANG
CUPCAKE BIRTHDAY CAKE CANDLE WISH PARTY HAT GOODYBAG PINATA
BALLOON ANIMAL FACEPAINT CLOWN MAGICIAN PUPPET SHOW THEATER
DINOSAUR DRAGON UNICORN PRINCESS KNIGHT CASTLE TREASURE MAP
PIRATE SHIP MERMAID FAIRY WIZARD WAND SPELL POTION MAGIC
ROBOT SPACESHIP ALIEN PLANET STAR COMET ROCKET BLASTOFF
PUPPY KITTEN BUNNY HAMSTER GOLDFISH TURTLE PARROT GUINEA
`,
  animals_more: `
WOLF FOX HYENA JACKAL DINGO COYOTE DHOLE CARACAL SERVAL OCELOT
MARGAY OCELOT BOBCAT WILDCAT LYNX PUMA PUMA LIONESS TIGERESS
PANTHER LEOPARD SNOWLEOPARD CLOUDED CHEETAH JAGUARUNDI
TAPIR CAPYBARA AGOUTI PACAS MARA VICUÑA GUANACO
MANATEE DUGONG PORPOISE BELUGA BOWHEAD HUMPBACK SPERMWHALE
BLUEWHALE GRAYWHALE RIGHTWHALE MINKE FINWHALE PILOTWHALE
ALBATROSS PETREL SHEARWATER PUFFIN AUK MURRE GUILLEMOT
KINGPENGUIN EMPERORPENGUIN ADELIE CHINSTRAP ROCKHOPPER
AXOLOTL NEWT CAECILIAN NEWT SKINK GECKO MONITOR IGUANA
ANACONDA PYTHON BOA VIPER COBRA MAMBA ADDER RATTLESNAKE
`,
};

function tokenize(blob) {
  return blob
    .toUpperCase()
    .replace(/[^A-Z\s]/g, ' ')
    .split(/\s+/)
    .map((w) => w.trim())
    .filter((w) => w.length >= 3 && w.length <= 14);
}

function expandBanks() {
  const file = path.join(root, 'src/lib/wordBanks.ts');
  let src = fs.readFileSync(file, 'utf8');

  const map = {
    mythology: EXTRA.mythology,
    history: EXTRA.history,
    travel: EXTRA.travel,
    technology: EXTRA.technology,
    movies: EXTRA.movies + ' ' + EXTRA.movies_more,
    holiday: EXTRA.holiday,
    kids: EXTRA.kids,
    animals: EXTRA.animals_more,
  };

  for (const [cat, blob] of Object.entries(map)) {
    const re = new RegExp(`(${cat}:\\s*\\[)([\\s\\S]*?)(\\n  \\],)`);
    const m = src.match(re);
    if (!m) {
      console.warn('skip', cat);
      continue;
    }
    const existing = [...m[2].matchAll(/'([A-Z][A-Z0-9]*)'/g)].map((x) => x[1]);
    const added = tokenize(blob);
    const merged = [...new Set([...existing, ...added])].filter(
      (w) => w.length >= 3 && w.length <= 14,
    );
    const lines = [];
    for (let i = 0; i < merged.length; i += 6) {
      const chunk = merged.slice(i, i + 6).map((w) => `'${w}'`);
      lines.push(`    ${chunk.join(', ')},`);
    }
    src = src.replace(re, `$1\n${lines.join('\n')}$3`);
    console.log(cat, existing.length, '->', merged.length);
  }

  fs.writeFileSync(file, src);
}

const PACK_POOLS = {
  'ocean-creatures': `
WHALE DOLPHIN SHARK CORAL REEF OCTOPUS SQUID CRAB LOBSTER SEAL WALRUS
ORCA MANATEE NARWHAL STINGRAY JELLYFISH SEAHORSE SALMON TURTLE PENGUIN
PELICAN HERON ANEMONE KRILL PLANKTON CURRENT TIDE WAVE LAGOON ABYSS
STARFISH URCHIN CLAM OYSTER MUSSEL KELP ALGAE WHIRLPOOL PORPOISE
BELUGA HUMPBACK SPERMWHALE BLUEWHALE GRAYWHALE PILOTWHALE DUGONG
SEALION OTTER BEAVER FISHHOOK ANCHOR BUOY HARBOR MARINA PIER DOCK
TRAWLER SCHOONER YACHT CATAMARAN SAILBOAT SUBMARINE SCUBA SNORKEL
DEPTH PRESSURE SALINITY CURRENT EDDY UPWELLING THERMOCLINE TRENCH
MARIANA ABYSSAL BENTHIC PELAGIC NERITIC LITTORAL INTERTIDAL ESTUARY
MANGROVE SEAGRASS SARGASSUM PHYTOPLANKTON ZOOPLANKTON KRILL SWARM
SCHOOL SHOAL POD FLOCK COLONY BREEDING MIGRATION SPAWNING HATCH
FIN FLUKE BLOWHOLE DORSAL PECTORAL GILL SCALE FINRAY TENTACLE
INK CAMOUFLAGE BIOLUMINESCENT LURE ANGLERFISH MORAY EEL BARRACUDA
GROUPER SNAPPER TUNA MARLIN SAILFISH SWORDFISH RAY SKATE CHIMAERA
`,
  'world-kitchen': `
PIZZA SUSHI TACOS RAMEN CURRY HUMMUS PASTA BREAD CHEESE GARLIC BASIL
SPAGHETTI RISOTTO GNOCCHI CROISSANT BAGUETTE GUACAMOLE AVOCADO NOODLE
DUMPLING SAFFRON PAPRIKA CINNAMON GINGER TURMERIC WASABI SOYSAUCE
OLIVE TRUFFLE BRIOCHE FOCACCIA CIABATTA NAAN PITA TORTILLA EMPANADA
TAMALE ENCHILADA BURRITO QUESADILLA FAJITA SALSA PICO GUAC
PHO BANHMI DIMSUM SPRINGROLL WONTON BAO SOBA UDON YAKISOBA
TEMPURA TERIYAKI MISO RAMYUN KIMCHI BULGOGI BIBIMBAP KEBAB FALAFEL
SHAWARMA COUSCOUS TAGINE PAELLA PASTRAMI BRISKET RIBS CHILI STEW
CHOWDER GAZPACHO BORSCHT GUMBO JAMBALAYA CREOLE CAJUN BBQ
MARINADE RUB GLAZE SAUCE GRAVY STOCK BROTH CONSOMME BISQUE
DESSERT TIRAMISU CREMEBRULEE PAVLOVA BAKLAVA CANNOLI ECLAIR
MACARON PROFITEROLE SORBET GELATO SUNDAE PARFAIT MOUSSE FLAN
HERB SPICE SEASONING GARNISH DRIZZLE SEAR ROAST BRAISE SAUTE
POACH STEAM GRILL SMOKE FERMENT PICKLE CURE BRINE MARINATE
CHEF SOUSCHEF PASTRY BAKER BUTCHER FISHMONGER GREENGROCER
`,
  'champion-league': `
SOCCER TENNIS HOCKEY RUGBY BOXING GOLF SURFING SKIING MARATHON
SPRINT RELAY MEDAL TROPHY STADIUM ARENA COACH GOALKEEPER STRIKER
OLYMPICS CHAMPION PLAYOFF VICTORY ATHLETE REFEREE UMPIRE WHISTLE
SCOREBOARD SCORE GOAL POINT FOUL PENALTY OFFSIDE CORNER KICK
DRIBBLE PASS TACKLE HEADER VOLLEY SERVE SMASH LOB ACE
RALLY DEUCE SET MATCH TOURNAMENT BRACKET SEED RANKING
LEAGUE DIVISION CONFERENCE PLAYOFFS FINALS SEMIFINAL QUARTER
GOLD SILVER BRONZE PODIUM PODIUM CEREMONY ANTHEM FLAG
TRAINING PRACTICE DRILL WARMUP STRETCH CONDITIONING ENDURANCE
STRENGTH AGILITY SPEED POWER BALANCE FLEXIBILITY RECOVERY
UNIFORM JERSEY CLEATS SPIKES HELMET PADS GLOVES GUARD
BAT RACKET CLUB STICK PUCK BALL NET HOOP RIM COURT
TRACK FIELD POOL LANE LANE ROPE HURDLE VAULT JUMP
THROW DISCUS JAVELIN SHOTPUT HAMMER RELAY BATON ANCHOR
CYCLING ROWING SAILING FENCING ARCHERY SHOOTING RIDING
JUDO KARATE TAEKWONDO WRESTLING SUMO MMA BOUT ROUND
`,
  'silver-screen': `
CINEMA MOVIE FILM REEL CAMERA LENS SCENE TAKE CUT EDIT
DIRECTOR ACTOR ACTRESS STAR CAST CREW EXTRA STUNT DOUBLE
SCRIPT SCREENPLAY DIALOGUE MONOLOGUE VOICEOVER NARRATION
SUBTITLE CAPTION DUBBING SOUNDTRACK SCORE COMPOSER THEME
TRAILER TEASER POSTER MARQUEE TICKET USHER POPCORN SODA
BLOCKBUSTER INDIE FESTIVAL OSCAR PREMIERE REDCARPET FLASH
THEATER SCREEN IMAX DOLBY STEREO SURROUND PROJECTOR
GENRE DRAMA COMEDY HORROR THRILLER ROMANCE WESTERN NOIR
ANIMATION DOCUMENTARY BIOPIC MUSICAL SEQUEL PREQUEL REMAKE
PLOT TWIST CLIFFHANGER FLASHBACK MONTAGE FADE DISSOLVE WIPE
PROTAGONIST ANTAGONIST VILLAIN HERO SIDEKICK MENTOR FOIL
BOXOFFICE BUDGET GROSS OPENING WEEKEND MATINEE MIDNIGHT
CRITIC REVIEW RATING STAR SPOILER ALERT CAMEO EXTRAS
STORYBOARD ANIMATIC REEL FOLEY ADR MIXING MASTERING
LIGHTING KEYLIGHT SILHOUETTE FOCUS APERTURE FRAME RATE
WIDESCREEN ASPECT RATIO CELLULOID DIGITAL 4K HDR
FRANCHISE SAGA TRILOGY SPINOFF CROSSOVER REBOOT HOMAGE
`,
  'wonders-of-earth': `
MOUNTAIN VALLEY CANYON RIVER OCEAN DESERT FOREST JUNGLE
GLACIER VOLCANO ISLAND PENINSULA ARCHIPELAGO ATOLL REEF
WATERFALL CASCADE RAPIDS DELTA ESTUARY LAGOON BAY GULF
CONTINENT COUNTRY CAPITAL CITY VILLAGE HAMLET METROPOLIS
EQUATOR TROPIC POLE ARCTIC ANTARCTIC HEMISPHERE LATITUDE
LONGITUDE MERIDIAN PRIME GREENWICH TIMEZONE CLIMATE
WEATHER MONSOON TYPHOON HURRICANE TORNADO BLIZZARD DROUGHT
RAINFOREST TAIGA TUNDRA SAVANNA PRAIRIE STEPPE PLAINS
PLATEAU MESA BUTTE RIDGE PEAK SUMMIT PASS TUNNEL BRIDGE
LANDMARK MONUMENT STATUE TEMPLE PYRAMID CASTLE FORTRESS
MUSEUM GALLERY PARK RESERVE SANCTUARY WILDERNESS TRAIL
EXPLORE MAP COMPASS NAVIGATE JOURNEY EXPEDITION TREK
SAFARI HIKE CLIMB CAMP BIVOUAC LOOKOUT VIEWPOINT SCENIC
HORIZON COASTLINE SHORELINE BOARDWALK MARINA HARBOR PORT
BORDER BOUNDARY FRONTIER TERRITORY PROVINCE STATE REGION
CULTURE LANGUAGE DIALECT CUSTOM TRADITION FESTIVAL LOCAL
PASSPORT VISA CURRENCY EXCHANGE MARKET BAZAAR SOUVENIR
PHOTOGRAPHY LANDSCAPE SUNRISE SUNSET GOLDENHOUR DAWN
`,
  'lab-coat': `
LABORATORY EXPERIMENT HYPOTHESIS THEORY EVIDENCE DATA
MICROSCOPE TELESCOPE SPECTROSCOPE CENTRIFUGE BEAKER FLASK
PIPETTE BURETTE TESTTUBE PETRIDISH SLIDE COVERSLIP STAIN
CHEMICAL ELEMENT COMPOUND MOLECULE ATOM ION ELECTRON
PROTON NEUTRON NUCLEUS ORBITAL BOND REACTION CATALYST
ENZYME PROTEIN DNA RNA CHROMOSOME GENE GENOME CELL
MITOSIS MEIOSIS MEMBRANE ORGANELLE MITOCHONDRIA NUCLEUS
PHOTOSYNTHESIS RESPIRATION FERMENTATION METABOLISM CYCLE
PHYSICS FORCE ENERGY MASS VELOCITY ACCELERATION MOMENTUM
GRAVITY FRICTION PRESSURE TEMPERATURE HEAT ENTROPY
WAVE FREQUENCY AMPLITUDE WAVELENGTH PHOTON LASER OPTICS
MAGNETISM CURRENT VOLTAGE RESISTANCE CIRCUIT BATTERY
BIOLOGY ECOLOGY EVOLUTION SPECIES HABITAT ECOSYSTEM
FOSSIL GEOLOGY MINERAL ROCK STRATA FOSSIL SEDIMENT
ASTRONOMY PLANET STAR GALAXY NEBULA QUASAR PULSAR
SCIENTIST RESEARCHER ANALYST TECHNICIAN PEER REVIEW
CONTROL VARIABLE SAMPLE POPULATION STATISTIC GRAPH
ACCURACY PRECISION ERROR UNCERTAINTY CALIBRATE MEASURE
DISCOVERY INVENTION INNOVATION BREAKTHROUGH PATENT
`,
  'symphony-hall': `
MUSIC MELODY HARMONY RHYTHM TEMPO BEAT MEASURE BAR
NOTE CHORD SCALE KEY MAJOR MINOR INTERVAL OCTAVE
SONATA SYMPHONY CONCERTO OVERTURE ARIA OPERA BALLET
ORCHESTRA CHOIR BAND ENSEMBLE QUARTET TRIO DUET SOLO
VIOLIN VIOLA CELLO BASS FLUTE CLARINET OBOE BASSOON
TRUMPET TROMBONE HORN TUBA SAXOPHONE PICCOLO HARP
PIANO ORGAN HARPSICHORD KEYBOARD GUITAR BANJO UKULELE
DRUM CYMBAL TIMPANI XYLOPHONE MARIMBA VIBRAPHONE GONG
CONDUCTOR BATON SCORE SHEET MUSIC STAFF CLEF SHARP
FLAT NATURAL REST DYNAMICS FORTE PIANO CRESCENDO
DIMINUENDO STACCATO LEGATO VIBRATO TREMOLO GLISSANDO
COMPOSER MAESTRO VIRTUOSO SOLOIST ACCOMPANIST SINGER
TENOR ALTO SOPRANO BARITONE BASS CHOIR CHORUS
GENRE CLASSICAL JAZZ BLUES ROCK POP FOLK COUNTRY
HIPHOP ELECTRONIC AMBIENT FUSION IMPROV JAM SESSION
CONCERT RECITAL REHEARSAL PRACTICE AUDITION STAGE
APPLAUSE ENCORE OVATION BOW CURTAIN CALL HALL
ACOUSTICS REVERB ECHO AMPLIFIER MICROPHONE MIXER
RECORDING STUDIO TRACK ALBUM SINGLE EP LP VINYL
`,
  'wild-trails': `
FOREST WOODLAND GROVE THICKET CLEARING MEADOW GLADE
TRAIL PATH FOOTPATH SWITCHBACK RIDGELINE SUMMIT PEAK
VALLEY RAVINE GORGE CANYON GULCH CREEK STREAM RIVER
WATERFALL CASCADE RAPIDS POOL POND LAKE MARSH SWAMP
MOSS LICHEN FUNGUS MUSHROOM FERN BRACKEN IVY VINE
OAK MAPLE PINE FIR SPRUCE CEDAR BIRCH ASPEN WILLOW
WILDFLOWER BLOOM BLOSSOM PETAL POLLEN NECTAR BEE
BUTTERFLY DRAGONFLY LADYBUG BEETLE ANT CRICKET FROG
BIRD SONG CALL NEST ROOST MIGRATION FLOCK FEATHER
DEER FOX BEAR WOLF COYOTE RACCOON SQUIRREL CHIPMUNK
HIKE TREK CLIMB SCRAMBLE BIVOUAC CAMP TENT SLEEPING
BACKPACK CANTEEN COMPASS MAP TRAILHEAD MARKER BLAZE
LOOKOUT VIEWPOINT SCENIC OVERLOOK HORIZON SUNRISE
SUNSET TWILIGHT DAWN DUSK STARLIGHT MOONLIGHT GLOW
WEATHER RAIN MIST FOG DEW FROST SNOW WIND BREEZE
CANOPY UNDERSTORY FLOOR LITTER HUMUS SOIL ROOT
SEEDLING SAPLING TIMBER LOGGING CONSERVE PROTECT
WILDLIFE HABITAT SANCTUARY RESERVE PARK WILDERNESS
`,
  'star-voyager': `
ROCKET SPACESHIP SHUTTLE CAPSULE MODULE PROBE SATELLITE
ORBIT APOGEE PERIGEE TRAJECTORY THRUST BOOSTER FUEL
ASTRONAUT COSMONAUT PILOT COMMANDER ENGINEER MISSION
CONTROL GROUNDCREW TELEMETRY UPLINK DOWNLINK SIGNAL
MOON LUNAR MARS MARTIAN VENUS MERCURY JUPITER SATURN
URANUS NEPTUNE PLUTO CERES ASTEROID COMET METEOR
NEBULA GALAXY QUASAR PULSAR MAGNETAR BLACKHOLE EVENT
HORIZON SINGULARITY ACCRETION DISK JET STELLAR SOLAR
WIND FLARE CORONA PHOTOSPHERE CHROMOSPHERE PROMINENCE
TELESCOPE OBSERVATORY SPECTRUM SPECTROSCOPY REDSHIFT
PARALLAX LIGHTYEAR PARSEC ASTRONOMICAL UNIT HUBBLE
WEBB KEPLER CASSINI VOYAGER PIONEER APOLLO GEMINI
ISS MIR TIANGONG SKYLAB SPACELAB DOCKING AIRLOCK
SPACEWALK EXTRAVEHICULAR SUIT HELMET GLOVE BOOT
WEIGHTLESS FLOAT MICROGRAVITY PRESSURE OXYGEN VACUUM
EXOPLANET HABITABLE GOLDILOCKS BIOSIGNATURE SETI
RADIO DISH ANTENNA WAVE EMISSION ABSORPTION LINE
COSMOS UNIVERSE MULTIVERSE INFLATION BIGBANG EXPANSION
DARKMATTER DARKENERGY COSMOLOGY ASTROPHYSICS STELLAR
`,
  'page-turner': `
BOOK PAGE CHAPTER VERSE STANZA POEM PROSE FICTION
NOVEL NOVELLA SHORTSTORY ANTHOLOGY SERIES SAGA TRILOGY
PLOT SETTING THEME CONFLICT CLIMAX RESOLUTION ARC
PROTAGONIST ANTAGONIST HERO VILLAIN MENTOR RIVAL
NARRATOR DIALOGUE MONOLOGUE FORESHADOW FLASHBACK
METAPHOR SIMILE SYMBOLISM IMAGERY IRONY SATIRE
GENRE FANTASY MYSTERY THRILLER ROMANCE HORROR EPIC
LIBRARY BOOKSTORE SHELF STACK READING READER AUTHOR
WRITER NOVELIST POET EDITOR AGENT PUBLISHER IMPRINT
HARDCOVER PAPERBACK EBOOK AUDIOBOOK MANUSCRIPT DRAFT
REVISION EDIT PROOFREAD TYPESET BINDING COVER JACKET
BLURB SYNOPSIS OUTLINE STORYBOARD CHARACTER BACKSTORY
WORLDBUILDING UNIVERSE SEQUEL PREQUEL SPINOFF CANON
CLASSIC MASTERPIECE LITERATURE CRITICISM SCHOLARSHIP
THESIS JOURNAL DIARY LETTERS CORRESPONDENCE ARCHIVE
PARCHMENT SCROLL CODEX QUILL INK PEN PAPER PULP
BESTSELLER AWARD PULITZER BOOKER NOBEL PRIZE
BOOKCLUB DISCUSSION CRITIC REVIEW RATING STAR
FOLKLORE STORYTELLING ORAL TRADITION MYTH LEGEND
`,
  'long-words': `
PHOTOSYNTHESIS CHROMOSOME LABORATORY MICROSCOPE EVOLUTION
ATMOSPHERE HYDROSPHERE BIODIVERSITY CHROMATOGRAPHY SPECTROSCOPY
MITOCHONDRIA ENDANGERED EXPERIMENT HYPOTHESIS SCIENTIFIC
MOLECULES RADIATION GRAVITATION TELESCOPE ASTROPHYSICS
REFRIGERATOR EXTRAORDINARY COMMUNICATION INTERNATIONAL
CONSTITUTION REVOLUTIONARY UNDERSTANDING OPPORTUNITY
ENVIRONMENT ARCHITECTURE RESPONSIBILITY CHARACTERISTIC
TEMPERATURE ELECTRICITY MAGNETISM ACCELERATION VELOCITY
TRANSFORMATION DOCUMENTARY CINEMATOGRAPHY PHOTOGRAPHY
ENCYCLOPEDIA DICTIONARY VOCABULARY PRONUNCIATION
MATHEMATICS GEOMETRY ALGEBRA CALCULUS STATISTICS
BIOCHEMISTRY MICROBIOLOGY EPIDEMIOLOGY IMMUNOLOGY
PHILOSOPHY PSYCHOLOGY SOCIOLOGY ANTHROPOLOGY HISTORY
GEOGRAPHY TOPOGRAPHY CARTOGRAPHY NAVIGATION
TRANSPORTATION INFRASTRUCTURE COMMUNICATION NETWORK
TECHNOLOGY ENGINEERING MANUFACTURING INDUSTRIAL
AGRICULTURE HORTICULTURE VITICULTURE AQUACULTURE
CONSERVATION PRESERVATION RESTORATION REGENERATION
CELEBRATION FESTIVITY HOSPITALITY GENEROSITY KINDNESS
`,
  'spooky-search': `
GHOST WITCH PUMPKIN CANDLE SPIDER SKELETON MONSTER
HAUNTED GOBLIN VAMPIRE ZOMBIE MUMMY BROOM CAULDRON
CANDY MASK COSTUME SPOOKY CREEPY SHADOW NIGHT BAT
HOWL SCREAM SHRIEK GROAN CREAK RATTLE CHAIN COFFIN
GRAVEYARD TOMBSTONE CRYPT MAUSOLEUM CEMETERY VAULT
WEREWOLF BANSHEE PHANTOM SPECTER WRAITH POLTERGEIST
CURSE HEX SPELL CHARM POTION ELIXIR VENOM POISON
LANTERN JACKOLANTERN CANDLELIGHT FLICKER GLOW EMBER
FOG MIST HAZE TWILIGHT MIDNIGHT WITCHING HOUR
BLACK CAT CROW RAVEN OWL TOAD NEWT EYE OF NEWT
FANG CLAW TALON WING HORN TAIL FUR HIDE SCALE
DUNGEON CASTLE TOWER TURRET DRAWBRIDGE MOAT
LABYRINTH MAZE SECRET PASSAGE HIDDEN DOOR KEY
TREASURE CHEST BONES SKULL RIBCAGE SPINE GRAVE
TRICK TREAT BOO SCARE JUMPSCARE CHILL SHIVER
AUTUMN FALL LEAF ORANGE BLACK PURPLE ORANGE
HARVEST MOON FULLMOON CRESCENT ECLIPSE DARK
`,
  'winter-fest': `
SNOWMAN SLEIGH REINDEER STOCKING WREATH TINSEL HOLLY
MISTLETOE CAROL GIFT FIREPLACE EVERGREEN CANDLE SNOW
FROST ICICLE COCOA COOKIE CHIMNEY SANTA ELF BELL
SNOWFLAKE BLIZZARD FLURRY POWDER DRIFT SNOWBALL
ICE SKATE SLEDDING TOBOGGAN SKIING SNOWBOARD BOOTS
MITTEN GLOVE SCARF HAT PARKA COAT SWEATER WOOL
FIREPLACE HEARTH MANTEL LOG FLAME EMBER GLOW
GINGERBREAD SHORTBREAD PEPPERMINT CANDYCANE FUDGE
HOTCHOCOLATE MARSHMALLOW EGGNOG CIDER MULLED SPICE
ORNAMENT BAUBLE TREE TOPPER STAR ANGEL LIGHTS
GARLAND RIBBON BOW WRAPPER TAG CARD ENVELOPE
NORTHPOLE WORKSHOP TOY TRAIN DOLL BEAR BLOCKS
MIDNIGHT COUNTDOWN NEWYEAR RESOLUTION TOAST KISS
FESTIVE CHEER JOY PEACE LOVE HOPE WISH DREAM
FAMILY GATHERING FEAST TABLE BANQUET TOAST CHEERS
LANTERN FAIRYLIGHT STRING GLOW SHIMMER SPARKLE
SLEIGHBELLS RUDOLPH DASHER DANCER PRANCER VIXEN
COMET CUPID DONNER BLITZEN CLAUS MRSCLAUS
WINTER SOLSTICE DECEMBER JANUARY FROSTY CHILL
`,
  'myths-legends': `
ZEUS HERA ATHENA APOLLO ARTEMIS ARES HERMES HADES
POSEIDON DEMETER HESTIA DIONYSUS APHRODITE HEPHAESTUS
PERSEUS HERCULES ACHILLES ODYSSEUS ORION MEDUSA
PEGASUS MINOTAUR CERBERUS HYDRA PHOENIX SPHINX TITAN
OLYMPUS ORACLE TEMPLE TRIDENT SHIELD CHARIOT NYMPH
SIREN CYCLOPS CENTAUR SATYR GRYPHON VALKYRIE ODIN
THOR LOKI FREYA ASGARD RAVEN HAMMER RUNE SAGA
LEGEND MYTH GODDESS HERO QUEST LABYRINTH UNDERWORLD
AMBROSIA NECTAR FATE MUSE PROPHECY RITUAL ALTAR
DIVINE IMMORTAL MORTAL REBIRTH CHAOS COSMOS CREATION
ATLANTIS TROY SPARTA DELPHI THEBES ARGOS TROY
PROMETHEUS PANDORA ICARUS DAEDALUS THESEUS ARIADNE
ATLAS CRONUS RHEA GAEA URANUS STYX LETHE CHARON
SCYLLA CHARYBDIS ARGUS GORGON HARPY FURY MERMAID
DRAGON WYVERN KRAKEN LEVIATHAN CHIMERA UNICORN
VALHALLA BIFROST MIDGARD YGGDRASIL FENRIR MJOLNIR
SPELL CHARM AMULET TALISMAN RELIC ARTIFACT EPIC
`,
  'time-capsule': `
EMPIRE DYNASTY KINGDOM REPUBLIC SENATE PHARAOH EMPEROR
QUEEN KNIGHT CASTLE SIEGE TREATY REVOLUTION COLONIAL
MEDIEVAL RENAISSANCE INDUSTRIAL ANCIENT CLASSICAL ERA
EPOCH CENTURY DECADE ARCHIVE SCROLL MANUSCRIPT
CHRONICLE BATTLE VICTORY DEFEAT ALLIANCE DIPLOMACY
EXPLORER VOYAGE DISCOVERY INVENTION PRINTING COMPASS
PYRAMID TEMPLE FORUM COLOSSEUM AQUEDUCT MONUMENT
RUIN ARTIFACT RELIC MUSEUM EXHIBIT CIVILWAR WORLDWAR
REVOLT REFORM CONSTITUTION DEMOCRACY MONARCHY FEUDAL
NOBILITY PEASANT MERCHANT TRADE SILKROAD CARAVAN
NAVY ARMY GENERAL CAPTAIN LEGION PHALANX CATAPULT
CANNON PARLIAMENT CONGRESS PRESIDENT LIBERTY JUSTICE
HERITAGE LEGACY VIKING NORMAN SAXON CELTIC ROMAN
GREEK PERSIAN BABYLON ASSYRIA MESOPOTAMIA EGYPT
CLEOPATRA CAESAR AUGUSTUS CHARLEMAGNE NAPOLEON
WASHINGTON LINCOLN REVOLUTION INDUSTRY STEAM ENGINE
TELEGRAPH RAILROAD FRONTIER PIONEER SETTLER HOMESTEAD
GUTENBERG ENLIGHTENMENT REFORMATION BAROQUE VICTORIAN
`,
  'passport-stamps': `
PASSPORT LUGGAGE SUITCASE BACKPACK TICKET BOARDING
AIRPORT RUNWAY CABIN PILOT FLIGHT LAYOVER HOTEL
HOSTEL RESORT LODGE CAMPING MAP COMPASS GUIDE
ITINERARY JOURNEY VOYAGE CRUISE TRAIN RAILWAY
STATION METRO TAXI BUS FERRY HARBOR PORT DOCK
PIER BEACH ISLAND COAST MOUNTAIN VALLEY DESERT
JUNGLE FOREST CANYON WATERFALL LAGOON REEF CITY
CAPITAL VILLAGE MARKET BAZAAR PLAZA MUSEUM GALLERY
TEMPLE CHURCH MOSQUE PALACE CASTLE BRIDGE TOWER
LANDMARK MONUMENT STATUE SOUVENIR PHOTO CAMERA
SUNSET SUNRISE HORIZON ADVENTURE EXPLORE WANDER
TRAIL HIKING SAFARI DIVING SNORKEL SKIING SURFING
SAILING VISA CUSTOMS BORDER CURRENCY EXCHANGE
TERMINAL GATE CONCOURSE BAGGAGE CLAIM CAROUSEL
CONCIERGE RECEPTION SUITE VILLA CHALET COTTAGE
SAFARI EXPEDITION TREK ZIPLINE PARASAIL SCUBA
CULTURE CUISINE LANGUAGE CUSTOM FESTIVAL LOCAL
GUIDEBOOK NAVIGATE DISCOVER WANDERLUST NOMAD TRIP
VACATION GETAWAY RETREAT TOURISM TRAVELER SCENIC
`,
  'digital-frontier': `
COMPUTER LAPTOP TABLET PHONE SCREEN KEYBOARD MOUSE
CURSOR PIXEL SOFTWARE HARDWARE NETWORK INTERNET
BROWSER WEBSITE SERVER CLOUD DATA CODE SCRIPT
PROGRAM ALGORITHM BINARY BYTE ROUTER MODEM WIFI
BLUETOOTH SIGNAL BATTERY CHARGER CABLE PORT CHIP
CIRCUIT SENSOR CAMERA SPEAKER HEADPHONE MICROPHONE
DISPLAY ROBOT DRONE SATELLITE GPS APP UPDATE
DOWNLOAD UPLOAD STREAM CACHE MEMORY STORAGE
DATABASE QUERY ENCRYPT PASSWORD LOGIN ACCOUNT
FIREWALL VIRUS MALWARE BACKUP RESTORE SYNC
VECTOR RENDER ENGINE PLUGIN WIDGET DESKTOP MOBILE
WEARABLE SMARTWATCH CONSOLE GAMING PRINTER SCANNER
MONITOR PROJECTOR LASER QUANTUM NEURAL ROBOTICS
AUTOMATION DIGITAL VIRTUAL PROCESSOR MICROCHIP
FIRMWARE KERNEL DRIVER MODULE LIBRARY FRAMEWORK
COMPILER DEBUGGER REPOSITORY BRANCH COMMIT MERGE
DEPLOYMENT PIPELINE CONTAINER DOCKER API ENDPOINT
LATENCY BANDWIDTH PACKET PROTOCOL ENCRYPTION TOKEN
FRONTEND BACKEND TYPESCRIPT PYTHON RUST GOLANG
MACHINELEARNING TENSOR MODEL TRAINING INFERENCE
`,
};

function expandPacks() {
  const file = path.join(root, 'src/lib/packLevels.ts');
  let src = fs.readFileSync(file, 'utf8');

  const blocks = [];
  for (const [id, blob] of Object.entries(PACK_POOLS)) {
    const words = [...new Set(tokenize(blob))].filter((w) => w.length >= 3 && w.length <= 14);
    console.log('pack', id, words.length);
    const lines = [];
    for (let i = 0; i < words.length; i += 6) {
      const chunk = words.slice(i, i + 6).map((w) => `'${w}'`);
      lines.push(`    ${chunk.join(', ')},`);
    }
    blocks.push(`  '${id}': [\n${lines.join('\n')}\n  ],`);
  }

  const newPools = `export const PACK_WORD_POOLS: Partial<Record<string, string[]>> = {\n${blocks.join('\n')}\n};\n`;
  src = src.replace(
    /export const PACK_WORD_POOLS: Partial<Record<string, string\[\]>> = \{[\s\S]*?\n\};\n/,
    newPools,
  );
  fs.writeFileSync(file, src);
}

expandBanks();
expandPacks();
console.log('done');
